skpi_management_app/urls.py
from unicodedata import name
from django.urls import path

from skpi_management_app import StaffViews, StudentViews,adminHome
from . import views



urlpatterns = [
    path('',views.loginPage,name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('update_user/<int:user_id>/',adminHome.update_user,name='update_user'),
    path('view_user_staff/<int:user_id>/',adminHome.view_user_staff,name='view_user_staff'),
    path('view_user_mahasiswa/<int:user_id>/',adminHome.view_user_mahasiswa,name='view_user_mahasiswa'),
    path('get_user_details/',views.get_user_details,name='get_user_details'),
    path('admin_home/',adminHome.admin_home,name='admin_home'),
    path('admin_profile/',adminHome.admin_profile,name='admin_profile'),
    path('check_email_exist/', adminHome.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', adminHome.check_username_exist, name="check_username_exist"),

    #perguruan tinggi
    path('manage_perguruan_tinggi/',adminHome.manage_perguruantinggi,name='manage_perguruan_tinggi'),
    path('hapus_perguruan_tinggi/<int:perguruantinggi_id>/',adminHome.hapus_perguruantinggi,name='hapus_perguruan_tinggi'),
    path('update_perguruan_tinggi/<int:perguruantinggi_id>/update',adminHome.edit_perguruantinggi,name='edit_perguruan_tinggi'),
    path('manage_fakultas/',adminHome.manage_fakultas,name='manage_fakultas'),
    path('hapus_fakultas/<int:fakultas_id>/',adminHome.hapus_fakultas,name='hapus_fakultas'),
    path('update_fakultas/<int:fakultas_id>/',adminHome.update_fakultas,name='update_fakultas'),
    path('manage_programstudi/',adminHome.manage_programstudi,name='manage_programstudi'),
    path('update_programstudi/<int:programstudi_id>',adminHome.update_programstudi,name='update_programstudi'),
    path('view_programstudi_detail/<int:programstudi_id>/',adminHome.view_programstudi_detail,name='view_programstudi_detail'),

    #staff/admin
    path('manage_staff/',adminHome.manage_staff,name='manage_staff'),
    path('add_staff/',adminHome.add_staff,name='add_staff'),
    path('add_staff_save/',adminHome.add_staff_save,name="add_staff_save"),
    path('edit_staff/<int:staff_id>/',adminHome.edit_staff,name="edit_staff"),
    path('hapus_staff/<int:staff_id>/',adminHome.hapus_staff,name='hapus_staff'),
    path('view_user_staff/<int:staff_id>/',adminHome.view_user_staff,name='view_user_staff'),

    

    #mahasiswa/admin
    path('manage_mahasiswa/',adminHome.manage_mahasiswa,name='manage_mahasiswa'),
    path('manage_user_mahasiswa/',adminHome.manage_user_mahasiswa,name='manage_user_mahasiswa'),
    path('add_mahasiswa/',adminHome.add_mahasiswa,name='add_mahasiswa'),
    path('add_mahasiswa_save/', adminHome.add_mahasiswa_save,name='add_mahasiswa_save'),
    path('hapus_mahasiswa/<int:mahasiswa_id>/',adminHome.hapus_mahasiswa,name='hapus_mahasiswa'),
    path('update_mahasiswa/<int:user_id>/',adminHome.update_mahasiswa,name='update_mahasiswa'),

    #mahasiswa/
    path('mahasiswa_home/',StudentViews.student_home,name='student_home'),
    path('student_view/',StudentViews.view_mahasiswa,name='student_view'),

    #gelar
    path('manage_gelar/',adminHome.manage_gelar,name='manage_gelar'),
    path('update_gelar/<int:gelar_id>/',adminHome.update_gelar,name='update_gelar'),
    path('manage_cpl/',adminHome.manage_cpl,name='manage_cpl'),
    path('update_cpl/<int:cpl_id>/',adminHome.update_cpl,name='update_cpl'),
    path('hapus_cpl/<int:cpl_id>/',adminHome.hapus_cpl,name='hapus_cpl'),
    path('manage_subcpl/',adminHome.manage_subcpl,name='manage_subcpl'),
    path('update_subcpl/<int:subcpl_id>/',adminHome.update_subcpl,name='update_subcpl'),
    path('hapus_subcpl/<int:subcpl_id>/',adminHome.hapus_subcpl,name='hapus_subcpl'),

    #staff
    path('staff_home/',StaffViews.staff_home,name='staff_home'),
    path('staff_manage_mahasiswa/',StaffViews.manage_mahasiswa,name='staff_manage_mahasiswa'),
    path('staff_add_mahasiswa/',StaffViews.add_mahasiswa,name='staff_add_mahasiswa'),
    path('staff_add_mahasiswa_save/', StaffViews.add_mahasiswa_save,name='staff_add_mahasiswa_save'),
    path('staff_hapus_mahasiswa/<int:mahasiswa_id>/',StaffViews.hapus_mahasiswa,name='staff_hapus_mahasiswa'),
    path('staff_check_email_exist/', StaffViews.staff_check_email_exist, name="staff_check_email_exist"),
    path('staff_check_username_exist/', StaffViews.staff_check_username_exist, name="staff_check_username_exist"),
    path('staff_update_mahasiswa/<int:user_id>/',StaffViews.update_mahasiswa,name='staff_update_mahasiswa'),
    path('staff_skpi_mahasiswa/<int:user_id>/',StaffViews.view_mahasiswa_skpi,name='staff_skpi_mahasiswa'),


    #pelatihan/admin
    path('manage_pelatihan/',adminHome.manage_pelatihan,name='manage_pelatihan'),
    path('add_pelatihan/',adminHome.add_pelatihan,name='add_pelatihan'),
    path('add_pelatihan_save/', adminHome.add_pelatihan_save,name='add_pelatihan_save'),
    path('hapus_pelatihan/<int:pelatihan_id>/', adminHome.hapus_pelatihan,name='hapus_pelatihan'),
    path('update_pelatihan/<int:pelatihan_id>/', adminHome.update_pelatihan,name='update_pelatihan'),

    #pelatihan/mahasiswa
    path('mahasiswa_pelatihan/',StudentViews.mahasiswa_manage_pelatihan,name='mahasiswa_manage_pelatihan'),
    path('mahasiswa_add_pelatihan/',StudentViews.mahasiswa_add_pelatihan,name='mahasiswa_add_pelatihan'),
    path('mahasiswa_add_pelatihan_save/',StudentViews.mahasiswa_add_pelatihan_save,name='mahasiswa_add_pelatihan_save'),
    path('mahasiswa_hapus_pelatihan/<int:pelatihan_id>/', StudentViews.mahasiswa_hapus_pelatihan,name='mahasiswa_hapus_pelatihan'),
    path('mahasiswa_update_pelatihan/<int:pelatihan_id>/', StudentViews.mahasiswa_update_pelatihan,name='mahasiswa_update_pelatihan'),

    #prestasi/admin
    path('manage_prestasi',adminHome.manage_prestasi,name='manage_prestasi'),
    path('add_prestasi/',adminHome.add_prestasi,name='add_prestasi'),
    path('add_prestasi_save/', adminHome.add_prestasi_save,name='add_prestasi_save'),
    path('hapus_prestasi/<int:prestasi_id>/', adminHome.hapus_prestasi,name='hapus_prestasi'),
    path('update_prestasi/<int:prestasi_id>/', adminHome.update_prestasi,name='update_prestasi'),

    #prestasi/mahasiswa
    path('mahasiswa_manage_prestasi',StudentViews.mahasiswa_manage_prestasi,name='mahasiswa_manage_prestasi'),
    path('mahasiswa_add_prestasi/',StudentViews.mahasiswa_add_prestasi,name='mahasiswa_add_prestasi'),
    path('mahasiswa_add_prestasi_save/',StudentViews.mahasiswa_add_prestasi_save,name='mahasiswa_add_prestasi_save'),
    path('mahasiswa_hapus_prestasi/<int:prestasi_id>/', StudentViews.mahasiswa_hapus_prestasi,name='mahasiswa_hapus_prestasi'),
    path('mahasiswa_update_prestasi/<int:prestasi_id>/', StudentViews.mahasiswa_update_prestasi,name='mahasiswa_update_prestasi'),



   


]

surat_pendamping_ijazah/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from surat_pendamping_ijazah import settings
#
from django.views.static import serve

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('skpi_management_app.urls')),
   # path('media/P<path>/)', serve,{'document_root': settings.MEDIA_ROOT}), 
    #path('static/<path>/)', serve,{'document_root': settings.STATIC_ROOT}), 
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skpi_management_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import  receiver


# Create your models here.
class CustomUser(AbstractUser):
    user_type_data = (
        (1,'HOD'),
        (2,'Staff'),
        (3,'Mahasiswa'),
    )
    user_type = models.CharField(default=1, choices=user_type_data,max_length=100)
    

class AdminHOD(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

class PerguruanTinggi(models.Model):
    nama = models.CharField(max_length=150, null=False, verbose_name='Nama PT')
    nosk = models.CharField(max_length=150, verbose_name='NO SK')
    logo = models.ImageField(upload_to='logo', max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
            verbose_name_plural = "Kampus"

    def __str__(self):
        return self.nama

class Fakultas(models.Model):
    nama = models.CharField(max_length=100, null=False, verbose_name='Fakultas')
    namasingkat = models.CharField(max_length=50, blank=True, verbose_name='Singkatan')
    kampus = models.ForeignKey(PerguruanTinggi, on_delete=models.CASCADE, verbose_name='Kampus', default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
            verbose_name_plural = "Fakultas"

    def __str__(self):
        return self.nama

class ProgramStudi(models.Model):
    kodeprodi = models.CharField(max_length=10, verbose_name='Kode Prodi')
    nama = models.CharField(max_length=150, null=False, verbose_name='Program Studi')
    namasingkat = models.CharField(max_length=150, null=False, verbose_name="Singkatan")
    JENJANG = (
        ('D3','DIPLOMA-3'),
        ('S1','STRATA-1'),
        ('S2','STRATA-2'),
        ('S3','STRATA-3'),
    )
    jenis = models.CharField(max_length=150,verbose_name='Jenis Program Pendidikan',blank=True)
    jenjang = models.CharField(max_length=150, choices=JENJANG, default='1')
    LEVEL = (
        ('1','level 1'),
        ('2','level 2'),
        ('3','level 3'),
        ('4','level 4'),
        ('5','level 5'),
        ('5','level 6'),
    )
    levelkualifikasi = models.CharField(max_length=20, verbose_name='Level Kualifikasi', blank=True,choices=LEVEL)
    persyaratan = models.CharField(max_length=100, verbose_name='Syarat Penerimaan', blank=True)
    noskakreditasi = models.CharField(max_length=20, blank=True, verbose_name='No.SK Akreditasi')
    nilaiakreditasi = models.CharField(max_length=50, verbose_name='Nilai Akreditasi', blank=True)
    lamastudi = models.CharField(max_length=10, verbose_name='Lama Studi', blank=True)
    sistempenilaian = models.TextField(verbose_name='Sistem Penilaian', blank=True)
    BAHASA=(
        ('Indonesia','Indonesia'),
        ('English','English')
    )
    bahasapengantar = models.CharField(max_length=20, verbose_name='Bahasa Pengantar', blank=True, choices=BAHASA)
    LANJUTAN = (
        ('D3','DIPLOMA-3'),
        ('S1','STRATA-1'),
        ('S2','STRATA-2'),
        ('S3','STRATA-3'),
    )
    Pendidikanlanjutan = models.CharField(max_length=50,verbose_name='Pindidikan Lanjut', blank=True,choices=LANJUTAN)
    fakultas = models.ForeignKey(Fakultas,on_delete=models.CASCADE)
    images = models.ImageField(upload_to='images_akreditasi')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
            verbose_name_plural = "Program Studi"
            unique_together = ['kodeprodi']


    def __str__(self):
        return self.nama


class Staff(models.Model):
    admin = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    address = models.TextField()
    programstudi = models.ForeignKey(ProgramStudi,on_delete=models.CASCADE, verbose_name="Program Studi",null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()


class Cpl(models.Model):
    namaindo = models.CharField(max_length=100, null=False,verbose_name='Aspek')
    namainggris = models.CharField(max_length=100, null=False,verbose_name='Attitude')
    programstudi = models.ForeignKey(ProgramStudi,on_delete=models.CASCADE, verbose_name='Program Studi')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
            verbose_name_plural = "Capaian Pembelajaran Lulusan"

    def __str__(self):
        return self.namaindo

class SubAspekCpl(models.Model):
    namaindo = models.CharField(max_length=255, null=True,blank=True, verbose_name='Sub Aspek')
    namainggris = models.CharField(max_length=100, null=False,verbose_name='Sub Attitude')
    cpl = models.ForeignKey(Cpl, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
            verbose_name_plural = "Sub Aspek Cpl"

    def __str__(self):
        return self.namaindo

class Gelar(models.Model):
    namasingkat = models.CharField(max_length=100, verbose_name='Gelar Singkat')
    nama = models.CharField(max_length=100, verbose_name='Gelar')
    programstudi = models.ForeignKey(ProgramStudi,on_delete=models.CASCADE,default=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Gelar Pendidikan"

    def __str__(self):
        return self.namasingkat+" - "+self.nama


class Mahasiswa(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    nim = models.CharField(max_length=30, blank=True,null=True)
    JK = (
        ('LAKI-LAKI','LAKI-LAKI'),
        ('PEREMPUAN','PEREMPUAN'),
    )
    gender = models.CharField(max_length=50,choices=JK)
    address = models.TextField(blank=True,max_length=250,null=True)
    tempatlahir = models.CharField(max_length=200,null=True)
    tgllahir = models.DateField(auto_created=True,null=True)
    noseriijazah = models.CharField(max_length=150, blank=True, verbose_name='No. Seri Ijazah')
    tglmasukkuliah = models.DateField(auto_created=True,verbose_name='Tanggal Masuk', null=True)
    tglluluskuliah = models.DateField(auto_created=True, verbose_name='Tanggal Lulus',null=True)
    gelar = models.ForeignKey(Gelar, on_delete=models.CASCADE, verbose_name='Gelar', default=1)
    programstudi = models.ForeignKey(ProgramStudi,on_delete=models.CASCADE, blank=True, null=True, verbose_name="Program Studi")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()


    class Meta:
        verbose_name_plural = "Mahasiswa"

    def __str__(self):
        return self.nim+" - "+self.admin.first_name
    


class Skpi(models.Model):
    noseriijazah = models.CharField(max_length=150, blank=True, verbose_name='No. Seri Ijazah')
    tglmasukkuliah = models.DateField(auto_created=True,verbose_name='Tanggal Masuk', null=True)
    tglluluskuliah = models.DateField(auto_created=True, verbose_name='Tanggal Lulus',null=True)
    gelar = models.ForeignKey(Gelar, on_delete=models.CASCADE, verbose_name='Gelar', default=1)
    mahasiswa = models.ForeignKey(Mahasiswa, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Data SKPI"
    
    def __str__(self):
        return self.mahasiswa.admin

class Prestasi(models.Model):
    namaprestasi = models.CharField(max_length=150, blank=True, verbose_name='Nama Prestasi')
    tglkegiatan = models.DateField(auto_created=True,blank=True, verbose_name='Tanggal')
    penyelenggara = models.CharField(max_length=150, blank=True,verbose_name='Penyelenggara')
    atasnama = models.CharField(max_length=150, blank=True, verbose_name='Atas Nama Pribadi/Instansi')
    LEVEL = (
        ('Lokal','Lokal'),
        ('Nasional','Nasional'),
        ('Internasional','Internasional'),
    )
    tingkat = models.CharField(max_length=50, default='Lokal',choices=LEVEL)
    images = models.ImageField(upload_to='img_prestasi')
    mahasiswa = models.ForeignKey(Mahasiswa, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Prestasi"

    def __str__(self):
        return self.namaprestasi
    

class Pelatihan(models.Model):
    kegiatan = models.CharField(max_length=150, blank=True, verbose_name='Kegiatan')
    tglpelatihan = models.DateField(auto_created=True, verbose_name='Tgl. Pelatihan')
    penyelenggara = models.CharField(max_length=150, blank=True, verbose_name='Penyelenggara')
    status = models.CharField(max_length=150,blank=True,verbose_name='Status')
    image= models.ImageField(upload_to='img_pelatihan',null=False, verbose_name='Image')
    mahasiswa = models.ForeignKey(Mahasiswa,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
   
    class Meta:
        verbose_name_plural = "Pelatihan"


    def __str__(self):
        return self.kegiatan

class Organisasi(models.Model):
    nama = models.CharField(max_length=150, blank=True, verbose_name='Nama Organisasi')
    periode = models.CharField(max_length=150, blank=True, verbose_name='Periode')
    jabatan = models.CharField(max_length=150, blank=True, verbose_name='Jabatan')
    berkaspendukung = models.CharField(max_length=150, blank=True, verbose_name='Berkas Pendukung')

skpi_management_app/templates/hod_template/add_mahasiswa_template.html
{% extends "hod_template/base_template.html" %}
{% block main_content %}
{% load crispy_forms_tags %}
<div class="page-heading">
    <h1 class="page-title">Halaman Mahasiswa</h1>
</div>
<div class="page-content fade-in-up">
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">
                Form Tambah Data
            </div>
        </div>
        <div class="ibox-body">
           <form method="POST" role="form" action="{% url 'add_mahasiswa_save' %}">
            {% csrf_token %}
            {% comment %} Display Messages {% endcomment %}
            {% if messages %}
            <div class="form-group">
                <div class="col-12 m-0">
                    {% for message in messages %}
                        {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% elif message.tags == "success" %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
                {{ form_mahasiswa|crispy}}
            <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
            <a href="{% url 'manage_mahasiswa' %}" class="btn btn-warning btn-sm">Batal</a>
           </form>
        </div>
    </div>
</div>
<!-- END PAGE CONTENT-->
{% endblock main_content %}

{% block custom_js %}
    {% comment %} Checking if email and username already exists or not usin Ajax {% endcomment %}

    <script>
        $(document).ready(function(){
            // keyup event will be triggered when user leaves keyboard
            $("#id_email").keyup(function(){
                var email = $(this).val();

                if(email!=""){
                    $.ajax({
                        url : '{% url 'check_email_exist' %}',
                        type : 'POST',
                        data : {email:email}
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: red; padding: 5px; font-weight: bold;'> Email Tidak Tersedia </span>").insertAfter("#id_email")
                        }
                        else{
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: green; padding: 5px; font-weight: bold;'> Email Tersedia. </span>").insertAfter("#id_email")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".email_error").remove();
                }
                
            })

            $("#id_username").keyup(function(){
                var username = $(this).val();
                
                if(username!=""){
                    $.ajax({
                        url : '{% url 'check_username_exist' %}',
                        type : 'POST',
                        data : {username:username}
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: red; padding: 5px; font-weight: bold;'> Username Tidak Tersedia. </span>").insertAfter("#id_username")
                        }
                        else{
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: green; padding: 5px; font-weight: bold;'> Username Tersedia. </span>").insertAfter("#id_username")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".username_error").remove();
                }
                
            })
        })
    </script>

{% endblock custom_js %}
    

skpi_management_app/templates/hod_template/add_organisasi_template.html
{% extends "hod_template/base_template.html" %}
{% block main_content %}
{% load crispy_forms_tags %}
<div class="page-heading">
    <h1 class="page-title">Organisasi</h1>
</div>
<div class="page-content fade-in-up">
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">
                Form Tambah Data
            </div>
        </div>
        <div class="ibox-body">
           <form method="POST" role="form"  action="{% url 'add_pelatihan_save' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% comment %} Display Messages {% endcomment %}
            {% if messages %}
            <div class="form-group">
                <div class="col-12 m-0">
                    {% for message in messages %}
                        {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% elif message.tags == "success" %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
                {{ form_pelatihan|crispy}}
            <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
            <a href="{% url 'manage_pelatihan' %}" class="btn btn-warning btn-sm">Batal</a>
           </form>
        </div>
    </div>
</div>
<!-- END PAGE CONTENT-->
{% endblock main_content %}

{% block custom_js %}
   

{% endblock custom_js %}
    

skpi_management_app/templates/hod_template/add_pelatihan_template.html
{% extends "hod_template/base_template.html" %}
{% block main_content %}
{% load crispy_forms_tags %}
<div class="page-heading">
    <h1 class="page-title">Halaman Pelatihan</h1>
</div>
<div class="page-content fade-in-up">
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">
                Form Tambah Data
            </div>
        </div>
        <div class="ibox-body">
           <form method="POST" role="form"  action="{% url 'add_pelatihan_save' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% comment %} Display Messages {% endcomment %}
            {% if messages %}
            <div class="form-group">
                <div class="col-12 m-0">
                    {% for message in messages %}
                        {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% elif message.tags == "success" %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
                {{ form_pelatihan|crispy}}
            <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
            <a href="{% url 'manage_pelatihan' %}" class="btn btn-warning btn-sm">Batal</a>
           </form>
        </div>
    </div>
</div>
<!-- END PAGE CONTENT-->
{% endblock main_content %}

{% block custom_js %}
    <script>

        $(document).ready(function(){
            $("#id_mahasiswa").select2();
        });

    </script>

{% endblock custom_js %}
    

skpi_management_app/templates/hod_template/edit_pelatihan_template.html
{% extends "hod_template/base_template.html" %}
{% load crispy_forms_tags %}
{% block main_content %}
<div class="row mt-2">
  <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="row">
                <div class="col-md-12 m-4">
                    <h4>Update Form </h4>
                    <div class="col-11 m-0">
                        {% for message in messages %}
                        {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% elif message.tags == "success" %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-md-11 mt-8 float-left">
                            <div class="card-body">
                                <form method="POST" role="form" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form_pelatihan|crispy}}
                                    <button type="submit" class="btn btn-primary btn-sm">Update</button>
                                    <a href="{% url 'manage_pelatihan' %}" class="btn btn-warning btn-sm">Batal</a>
                                </form>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>   
</div>
{% endblock main_content %}